### ISSUE TITLE
"ng serve" command is not working

### ISSUE THREAD

**Issue by mdfazuluddin** [pamtbaau/electron-angular-cli-sqlite-bootstrap#1]
Hi, 

I want to run the application in browser and for that I ran "ng serve" but its failing,
can you please check and provide the fix.

**Comment by pamtbaau** [comment]
I'm sorry, but the application is created to show how SQLite can be used in combination with Electron and Angular CLI. Therefor 'ng serve' is not tested and will not be fixed.
