### ISSUE TITLE
Live reload does not work properly

### ISSUE THREAD

**Issue by CRCameron** [pamtbaau/electron-angular-cli-sqlite-bootstrap#2]
When running build:electron and npm start together the live reload does not work properly. After a code change the app refreshes but shows a blank screen and devtools shows a message 'DevTools was disconnected from the page'. If you then cmd + r the app will show again with the changes updated.

This can actually be replicated just using cmd + r at anytime (without code changes). Every second refresh the page will show blank and then show the app again on the next refresh.

**Comment by pamtbaau** [comment]
Yes, I noticed it yesterday when upgrading the project I'm working on to the latest dependencies. Electron released a new patched version few days ago but still not working with Sql.

Try adding the following workaround `app.allowRendererProcessReuse = false;` to the top of `index.js`

**Comment by CRCameron** [comment]
Thanks @pamtbaau. That workaround has done the trick. Do you know if this is something that will get fixed in Electron? Or will the your solution no longer work in new Electron versions? As I get a warning saying allowRendererProcessReuse is deprecated.

**Comment by pamtbaau** [comment]
mapbox/node-sqlite is working on a fix. You could try the fix suggested in [this issue](https://github.com/mapbox/node-sqlite3/issues/1370#issuecomment-714323306)

**Comment by CRCameron** [comment]
@pamtbaau will do, thank again for you help
